import { registerEnumType } from "@nestjs/graphql";

export enum NotificationType {
    RIDE_REQUEST = 'RIDE_REQUEST',
    RIDE_CANCELLATION = 'RIDE_CANCELLATION',
    SCHEDULED_RIDE_NOTIFY = 'SCHEDULED_RIDE_NOTIFY',
    REAL_TIME_RIDE_TRACKING = 'REAL_TIME_RIDE_TRACKING',
    CHAT = 'CHAT',
    RIDE_COMPLETE_NOTIFICATION = 'RIDE_COMPLETE_NOTIFICATION',
    PROCEED_PAYMENT = 'PROCEED_PAYMENT',
    PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',
    PAYMENT_FAILURE = 'PAYMENT_FAILURE',
    PAYMENT_WITHDRAWAL = 'PAYMENT_WITHDRAWAL',
    TERMS_AND_CONDITIONS_UPDATED = 'TERMS_AND_CONDITIONS_UPDATED',
    RIDE_ACCEPTED = 'RIDE_ACCEPTED',
    RIDE_START = 'RIDE_START',
    RIDE_END = 'RIDE_END',
    REQUEST_TO_PAY = 'REQUEST_TO_PAY',
    DRIVER_ON_THE_WAY = 'DRIVER_ON_THE_WAY',
    PAYMENT_CONFIRM = 'PAYMENT_CONFIRM',
    WALLET_TOPUP = 'WALLET_TOPUP',
    WALLET_TOPUP_FAILED = 'WALLET_TOPUP_FAILED',
}
export enum PassengerNotificationType {
     RIDE_ACCEPTED =NotificationType.RIDE_ACCEPTED,
     RIDE_START = NotificationType.RIDE_START,
     RIDE_END = NotificationType.RIDE_END,
     REQUEST_TO_PAY = NotificationType.REQUEST_TO_PAY,
     DRIVER_ON_THE_WAY = NotificationType.DRIVER_ON_THE_WAY,
     SCHEDULED_RIDE_NOTIFY = NotificationType.SCHEDULED_RIDE_NOTIFY,
     REAL_TIME_RIDE_TRACKING = NotificationType.REAL_TIME_RIDE_TRACKING,
     CHAT = NotificationType.CHAT,
     RIDE_COMPLETE_NOTIFICATION = NotificationType.RIDE_COMPLETE_NOTIFICATION,
     PROCEED_PAYMENT = NotificationType.PROCEED_PAYMENT,
     TERMS_AND_CONDITIONS_UPDATED = NotificationType.TERMS_AND_CONDITIONS_UPDATED
}   
export enum DriverNotificationType {
    RIDE_REQUEST = NotificationType.RIDE_REQUEST,
    RIDE_CANCELLATION = NotificationType.RIDE_CANCELLATION,
    CHAT = NotificationType.CHAT,
    RIDE_COMPLETE_NOTIFICATION = NotificationType.RIDE_COMPLETE_NOTIFICATION,
    REAL_TIME_RIDE_TRACKING = NotificationType.REAL_TIME_RIDE_TRACKING,
    PAYMENT_CONFIRM = NotificationType.PAYMENT_CONFIRM,
    PAYMENT_FAILURE = NotificationType.PAYMENT_FAILURE,
    PAYMENT_WITHDRAWAL = NotificationType.PAYMENT_WITHDRAWAL,
    TERMS_AND_CONDITIONS_UPDATED = NotificationType.TERMS_AND_CONDITIONS_UPDATED
}

registerEnumType(NotificationType, { name: 'NotificationType' });
registerEnumType(PassengerNotificationType, { name: 'PassengerNotificationType' });
registerEnumType(DriverNotificationType, { name: 'DriverNotificationType' });